The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) CCconfig        6)  ucx/1.14.1         11) flexiblas/3.3.1
  2) gentoo/2023     7)  libfabric/1.18.0   12) imkl/2023.2.0
  3) gcccore/.12.3   8)  pmix/4.2.4         13) StdEnv/2023
  4) gcc/12.3        9)  ucc/1.2.0
  5) hwloc/2.9.1     10) openmpi/4.1.5
bootstrapping finished 

Traceback (most recent call last):
  File "/project/6086407/nileb3/QRNN-MPC/New Files July 23/cem/MountainCar_approximate_continuous_seed15.py", line 192, in <module>
    total_reward, data = cem.run_cem(ctrl, seed, env, train, iter=max_steps, render=False, prob = prob, nb_repeat_action=nb_repeat_action) # cem.run_cem(ctrl, env, train, iter=max_steps, render=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6086407/nileb3/QRNN-MPC/New Files July 23/cem/pytorch_cem/cem.py", line 216, in run_cem
    nb_episode_success += 1
    ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nb_episode_success' where it is not associated with a value
